### ISSUE TITLE
Adding the Apache-2.0 license file

### ISSUE THREAD

**Issue by topazus** [contour-terminal/boxed-cpp#10]
I opened a Red Hat Bugzilla ticket to introduce boxed-cpp into Fedora. I ignored the missing of the license file in the project, which the header file showed the Apache-2.0 license.

https://github.com/contour-terminal/boxed-cpp/blob/783cb74e95cbe06a52b468a73c14467e8f082cd1/include/boxed-cpp/boxed.hpp#L1-L13

Ref: https://bugzilla.redhat.com/show_bug.cgi?id=2245909

**Comment by Yaraslaut** [comment]
Thanks @topazus, this is indeed something we need to take care, will make a PR for this in a short
