### ISSUE TITLE
CMake improvement

### ISSUE THREAD

**Issue by topazus** [contour-terminal/boxed-cpp#8]
- Use install() to specify files that needed to be installed for boxed-cpp.
- It also can generate config files with `configure_package_config_file()` and `write_basic_package_version_file()`, so that other projects can find and use boxed-cpp.

The above improvements will facilitate the packaging of contour-terminal, since boxed-cpp is one of the dependencies of contour-terminal.

Ref: 
1. https://cmake.org/cmake/help/latest/command/install.html
2. https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html
3. https://github.com/contour-terminal/contour/blob/76f172e01b16bd024793f133edf65b866e2f0064/cmake/ContourThirdParties.cmake#L130-L131

**Comment by christianparpart** [comment]
Many thanks @topazus,

I'd love to have that. So far my CMake knowledge is pretty hands-on limited to what I needed and was sufficient so far. But I personally would really much prefer to have proper install targets also.

I've never heard of `configure_package_config_file()` nor `write_basic_package_version_file()` therefore just yet. Thanks for sharing. :)
